title:              Mark Warneke
email:              warneke.mark@outlook.com
description:        Personal Blog
author:             Mark Warneke
baseurl:            "/"
url:                "https://markwarneke.me"

# Social Profiles
twitter_username:   MarkWarneke
github_username:    MarkWarneke
linkedin_username:  MarkWarneke
#facebook_username:  StartBootstrap

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-70835200-1 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site